version: '3.8'

services:
  users_app:
    image: faceit/users:latest
    build:
      context: .
    container_name: users_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/faceit
      - SPRING_DATASOURCE_USERNAME=faceit
      - SPRING_DATASOURCE_PASSWORD=faceit
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  db:
    image: postgres:13.1-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=faceit
      - POSTGRES_PASSWORD=faceit



